import {expect,test} from "@playwright/test";

test("compares two drivers immediately from the standings",async({page})=>{await page.goto("/");const george=page.getByLabel("Compare George Russell with");await expect(george.locator("option").filter({hasText:"Kimi Antonelli (Gap: -66)"})).toHaveCount(1);await expect(george.locator("option").filter({hasText:"Lewis Hamilton (Gap: +10)"})).toHaveCount(1);await page.getByLabel("Compare Kimi Antonelli with").selectOption("George Russell");await expect(page.getByRole("heading",{name:"Kimi Antonelli vs George Russell"})).toBeVisible();await expect(page.getByText(/must be at least -65/)).toHaveCount(0);await expect(page.getByText("Complete winning rule")).toHaveCount(0);await expect(page.getByText("Head-to-head · not a championship prediction")).toHaveCount(0);await expect(page.getByText(/How Kimi Antonelli finishes ahead of George Russell/)).toHaveCount(0);await expect(page.getByText("Winning scenarios only")).toHaveCount(0);await expect(page.getByText("Position examples from the exact rule")).toHaveCount(0);await expect(page.getByText("Comparison complete.")).toHaveCount(0);await expect(page.getByText(/Losing contrast/)).toHaveCount(0)});

test("compares two constructors immediately from the standings",async({page})=>{await page.goto("/");await page.getByRole("button",{name:"Constructors"}).click();await page.getByLabel("Compare Scuderia Ferrari HP with").selectOption("Mercedes-AMG PETRONAS F1 Team");await expect(page.getByRole("heading",{name:"Scuderia Ferrari HP vs Mercedes-AMG PETRONAS F1 Team"})).toBeVisible();await page.getByText("Show upcoming race positions").first().click();await expect(page.locator(".sample-rail li").first()).toContainText(" + ")});

test("home derives its season and limits comparison to contenders",async({page},testInfo)=>{await page.goto("/");await expect(page.getByRole("heading",{name:"Formula 1 - 2026 Season"})).toBeVisible();await expect(page.getByText("Current standings",{exact:true})).toBeVisible();const rival=page.getByLabel("Compare Lando Norris with");await expect(rival.locator("option").filter({hasText:"Lando Norris"})).toHaveCount(0);await expect(rival.locator("option").filter({hasText:"Nico Hulkenberg"})).toHaveCount(0);await expect(page.getByLabel("Compare Nico Hulkenberg with")).toHaveCount(0);if(testInfo.project.name==="mobile")await expect(rival).toBeVisible();await rival.selectOption("Max Verstappen");await expect(page.getByRole("button",{name:"Back to standings"})).toBeVisible();await page.getByRole("button",{name:"Back to standings"}).click();await expect(page.getByRole("heading",{name:"Formula 1 - 2026 Season"})).toBeVisible()});

test("switches between the three winning scenario tabs",async({page})=>{await page.goto("/");await page.getByLabel("Compare Kimi Antonelli with").selectOption("George Russell");const tabs=page.getByRole("tab");await expect(tabs).toHaveCount(3);await expect(page.getByRole("tab",{name:"Closest points win"})).toHaveAttribute("aria-selected","true");await page.getByRole("tab",{name:"Stronger winning margin"}).click();await expect(page.getByRole("tabpanel")).toContainText("Stronger winning margin");await page.getByRole("tab",{name:"Maximum advantage"}).focus();await page.keyboard.press("ArrowLeft");await expect(page.getByRole("tab",{name:"Stronger winning margin"})).toBeFocused();await expect(page.getByRole("tabpanel")).toContainText("Stronger winning margin")});
