"use client";
import type {ChampionshipKind,ProductData,StandingView} from "../product/frozen-product-data";
import type {HeadToHeadResult} from "../product/head-to-head";
import {ResultProof} from "./result-proof";

function Selector({label,value,rows,exclude,onChange,accent}:{label:string;value:string;rows:readonly StandingView[];exclude:string;onChange:(value:string)=>void;accent?:boolean}){const selected=rows.find(row=>row.id===value);return <label className={`battle-selector${accent?" battle-selector--accent":""}`}><span>{label}</span><select value={value} onChange={event=>onChange(event.target.value)}><option value="">Choose contender</option>{rows.filter(row=>row.id!==exclude).map(row=><option key={row.id} value={row.id}>{row.id}</option>)}</select><strong>{selected?`${selected.points} PTS`:"—"}</strong></label>}

export function ComparisonWorkspace({kind,rows,remaining,targetId,rivalId,result,busy,error,onTarget,onRival,onCompare,onClear,onRetry}:{kind:ChampionshipKind;rows:readonly StandingView[];remaining:ProductData["remaining"];targetId:string;rivalId:string;result:HeadToHeadResult|null;busy:boolean;error:string|null;onTarget:(id:string)=>void;onRival:(id:string)=>void;onCompare:()=>void;onClear:()=>void;onRetry:()=>void}){
 const target=rows.find(row=>row.id===targetId),rival=rows.find(row=>row.id===rivalId),gap=target&&rival?target.points-rival.points:null,ready=Boolean(target&&rival);
 return <main className="battle-workspace" id="comparison-workspace"><header className="battle-intro"><p className="eyebrow">Head-to-head analysis</p><h2>Championship battle</h2><p>Compare two contenders to see the verified points condition between them and representative finishing examples.</p></header><section className="battle-builder" aria-label="Choose comparison"><div className="battle-selectors"><Selector label={kind==="driver"?"Driver 1":"Team 1"} value={targetId} rows={rows} exclude={rivalId} onChange={onTarget} accent/><Selector label={kind==="driver"?"Driver 2":"Team 2"} value={rivalId} rows={rows} exclude={targetId} onChange={onRival}/><div className="battle-gap"><span>Current gap</span><strong>{gap===null?"—":`${Math.abs(gap)} PTS`}</strong><small>{gap===null?"Choose both contenders":gap===0?"Level on points":gap>0?`In favour of ${targetId}`:`In favour of ${rivalId}`}</small></div></div><div className="battle-actions"><button className="battle-submit" onClick={onCompare} disabled={!ready||busy}>{busy?"Checking condition…":"Compare contenders"}<span aria-hidden="true">→</span></button>{targetId||rivalId?<button className="battle-clear" onClick={onClear}>Clear</button>:null}</div></section><section className="capability-note"><div><p className="eyebrow">What this comparison shows</p><strong>A verified head-to-head points condition—not every possible championship scenario.</strong><p>The examples illustrate representative closest, quickest, slowest, and maximum-margin paths for these two contenders.</p></div><dl><div><dt>Races</dt><dd>{remaining.races}</dd></div><div><dt>Sprints</dt><dd>{remaining.sprints}</dd></div><div><dt>Max points</dt><dd>{remaining.maximumPoints[kind].total}</dd></div></dl></section>{error?<section className="battle-error" role="alert"><div><p className="eyebrow">Comparison stopped</p><strong>{error}</strong></div><button onClick={onRetry}>Try again</button></section>:null}<section className="results-stage" aria-live="polite"><header><div><p className="eyebrow">Analysis</p><h3>{result?`${result.targetId} vs ${result.rivalId}`:"Representative examples"}</h3></div>{result?<span>Verified condition</span>:null}</header>{busy?<div className="result-empty" role="status"><b>Checking the head-to-head condition…</b><p>This may take a moment.</p></div>:result?<><p className="comparison-disclaimer"><strong>Head-to-head only.</strong> This establishes when {result.targetId} finishes ahead of {result.rivalId}; it does not by itself prove the overall championship winner.</p><ResultProof result={result}/></>:<div className="result-empty"><span aria-hidden="true">01 — 02</span><b>No comparison yet</b><p>Choose two contenders, then select “Compare contenders.”</p></div>}</section></main>
}
