"use client";
import { useRef,useState } from "react";
import type { ProductData,ChampionshipKind } from "../product/frozen-product-data";
import type { HeadToHeadResult } from "../product/head-to-head";
import {parseHeadToHeadResult} from "../product/head-to-head-result";
import {StandingsPanel} from "./standings-panel";
import {ScenarioDossier} from "./scenario-dossier";
async function reason(response:Response){try{const value:unknown=await response.json();if(value&&typeof value==="object"&&"reason" in value&&typeof value.reason==="string")return value.reason}catch{}return "The comparison could not be completed."}
export function ScenarioWorkbench({data}:{data:ProductData}){const[kind,setKind]=useState<ChampionshipKind>("driver"),[targetId,setTargetId]=useState<string|null>(null),[rivalId,setRivalId]=useState(""),[result,setResult]=useState<HeadToHeadResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[detail,setDetail]=useState(false),pending=useRef(false);
 function choose(id:string){setTargetId(id);setRivalId("");setResult(null);setError(null);setDetail(true)}
 function switchKind(next:ChampionshipKind){setKind(next);setTargetId(null);setRivalId("");setResult(null);setError(null);setDetail(false)}
 async function compare(){if(pending.current||!targetId||!rivalId)return;pending.current=true;setBusy(true);setError(null);setResult(null);try{const response=await fetch("/api/compare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,targetId,rivalId,dataVersion:data.dataVersion,ruleVersion:data.ruleVersion})});if(!response.ok)throw new Error(await reason(response));const value=parseHeadToHeadResult(await response.json());if(!value||value.targetId!==targetId||value.rivalId!==rivalId||value.dataVersion!==data.dataVersion)throw new Error("The server returned a stale or invalid comparison.");setResult(value)}catch(value){setError(value instanceof Error?value.message:"The comparison could not be completed.")}finally{pending.current=false;setBusy(false)}}
 return <div className={`workbench ${detail?"show-detail":"show-master"}`}><StandingsPanel kind={kind} rows={data.standings[kind]} selectedId={targetId} onKind={switchKind} onSelect={choose}/><ScenarioDossier data={data} kind={kind} targetId={targetId} rivalId={rivalId} result={result} busy={busy} error={error} onRival={id=>{setRivalId(id);setResult(null);setError(null)}} onCalculate={()=>void compare()} onBack={()=>{setDetail(false);requestAnimationFrame(()=>document.querySelector<HTMLElement>(".standing-row[aria-current=true]")?.focus())}}/></div>}
