"use client";
import Link from "next/link";
import type {ChampionshipKind,ProductData,StandingView} from "../product/frozen-product-data";

function signedGap(points:number,rivalPoints:number){const gap=points-rivalPoints;return `${gap>0?"+":""}${gap}`}

export function StandingsPanel({season,kind,remaining,rows,busy,onKind,onCompare}:{season:number;kind:ChampionshipKind;remaining:ProductData["remaining"];rows:readonly StandingView[];busy:boolean;onKind:(kind:ChampionshipKind)=>void;onCompare:(targetId:string,rivalId:string)=>void}){
 const contenders=rows.filter(row=>row.eligible),points=remaining.maximumPoints[kind],events=remaining.races+remaining.sprints;
 return <main className="standings standings--home" aria-label="Championship standings"><header className="standings__head"><div className="season-title"><h1>Formula 1 - {season} Season</h1><p className="eyebrow">Current standings</p></div><table className="remaining-table"><caption>Maximum points remaining</caption><thead><tr><th></th><th>Races</th><th>Sprints</th><th>Total</th></tr></thead><tbody><tr><th>Events</th><td>{remaining.races}</td><td>{remaining.sprints}</td><td>{events}</td></tr><tr><th>Max points</th><td>{points.races}</td><td>{points.sprints}</td><td>{points.total}</td></tr></tbody></table><div className="switch" aria-label="Championship"><button aria-pressed={kind==="driver"} onClick={()=>onKind("driver")}>Drivers</button><button aria-pressed={kind==="constructor"} onClick={()=>onKind("constructor")}>Constructors</button></div></header><div className="standings-table"><div className="table-head" aria-hidden="true"><span>Rank</span><span>Contender</span><span>Pts</span><span>Gap</span><span>Status</span><span>Compare</span></div><ol className="standings-list">{rows.map(row=><li key={row.id}><div className={`standing-row ${row.position===1?"standing-row--leader":row.eligible?"standing-row--contending":"standing-row--eliminated"}`}><span className="rank">{String(row.position).padStart(2,"0")}</span><span className="contender"><strong>{row.id}</strong></span><span className="number">{row.points}</span><span className="number gap">{row.gap===0?"LEAD":row.gap}</span><span className={`status ${row.position===1?"leader":row.eligible?"eligible":"eliminated"}`}>{row.eligible?"In contention":"Eliminated"}</span>{row.eligible?<label className="compare-cell"><span className="sr-only">Compare {row.id} with</span><select value="" disabled={busy} aria-label={`Compare ${row.id} with`} onChange={event=>{const rivalId=event.target.value;if(rivalId)onCompare(row.id,rivalId)}}><option value="">Select rival</option>{contenders.filter(rival=>rival.id!==row.id).map(rival=><option className={rival.points>row.points?"rival-option--ahead":rival.points<row.points?"rival-option--behind":""} key={rival.id} value={rival.id}>{rival.id} (Gap: {signedGap(row.points,rival.points)})</option>)}</select></label>:<span className="compare-unavailable" aria-label="Comparison unavailable">—</span>}</div></li>)}</ol><footer className="standings-privacy"><Link href="/privacy">Privacy</Link></footer></div></main>
}
