import { describe, expect, it } from "vitest";
import { approvedSnapshotFixture } from "../test/approved-frozen-fixture";
import { calculateHeadToHead } from "./head-to-head";
const snapshot=approvedSnapshotFixture();
const request=(kind:"driver"|"constructor",targetId:string,rivalId:string)=>({kind,targetId,rivalId,dataVersion:snapshot.dataVersion,ruleVersion:snapshot.ruleVersion});
describe("head-to-head comparison",()=>{
 it("returns the four named paths in their display order",()=>{const result=calculateHeadToHead(snapshot,request("driver","Kimi Antonelli","George Russell"));expect(result).toMatchObject({status:"COMPLETE",currentGap:66,requiredRemainingDifference:-65});if(result.status==="COMPLETE"){expect(result.examples.map(x=>x.title)).toEqual(["Closest Points Win","Quickest","Slowest","Maximum Points Win"]);expect(result.examples.filter(x=>!x.unavailableReason).every(x=>x.finalMargin!==null&&x.finalMargin>0&&x.events.length===11)).toBe(true)}});
 it("calculates the P1/P2 quickest path and a final-race slowest path",()=>{const result=calculateHeadToHead(snapshot,request("driver","Kimi Antonelli","George Russell"));if(result.status!=="COMPLETE")throw new Error("Expected a complete comparison");const quickest=result.examples[1],slowest=result.examples[2];expect(quickest.events.every(event=>event.includes("P1 (25) ·")||event.includes("P1 (8) ·"))).toBe(true);expect(quickest.events.every(event=>event.includes(": P2 (18)")||event.includes(": P2 (7)"))).toBe(true);expect(quickest.note).toMatch(/secured after the/);expect(slowest.note).toMatch(/remains undecided until the final race/);expect(slowest.finalMargin).toBe(1)});
 it("supports two-car team comparisons",()=>{const result=calculateHeadToHead(snapshot,request("constructor","Scuderia Ferrari HP","Mercedes-AMG PETRONAS F1 Team"));expect(result).toMatchObject({status:"COMPLETE",currentGap:-122,requiredRemainingDifference:123});if(result.status==="COMPLETE"){expect(result.examples.filter(x=>!x.unavailableReason).every(x=>x.events.every(e=>e.includes(" + ")))).toBe(true);expect(result.examples[1].events.every(event=>event.includes("P1 + P2")&&event.includes("P3 + P4"))).toBe(true)}});
 it("explains when the prescribed quickest path cannot win",()=>{const result=calculateHeadToHead(snapshot,request("driver","Lewis Hamilton","Kimi Antonelli"));if(result.status!=="COMPLETE")throw new Error("Expected a complete comparison");expect(result.examples[1]).toMatchObject({title:"Quickest",finalMargin:null,events:[]});expect(result.examples[1].unavailableReason).toMatch(/cannot secure this head-to-head/)});
 it("labels zero-point finishes below the scoring positions",()=>{const result=calculateHeadToHead(snapshot,request("driver","Lewis Hamilton","Kimi Antonelli"));if(result.status!=="COMPLETE")throw new Error("Expected a complete comparison");const events=result.examples.flatMap(example=>example.events);expect(events.some(event=>event.includes(":race —")&&event.includes("P11+ (0)"))).toBe(true);expect(events.some(event=>event.includes(":sprint —")&&event.includes("P9+ (0)"))).toBe(true);expect(events.every(event=>!event.includes("no points"))).toBe(true)});
 it("rejects the same competitor and stale data",()=>{expect(calculateHeadToHead(snapshot,request("driver","Kimi Antonelli","Kimi Antonelli"))).toMatchObject({status:"ERROR"});expect(calculateHeadToHead(snapshot,{...request("driver","Kimi Antonelli","George Russell"),dataVersion:"old"})).toMatchObject({status:"ERROR"})});
});
